payments.api.url=${PAYMENTS_API_URL}
monitorGui.url=${CHS_MONITOR_GUI_URL}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
welshLanguage.enabled=false

# Properties required by common-web-java
commonweb.cdn-url=//${CDN_HOST}
commonweb.chs-url=${CHS_URL}
commonweb.piwik-url=${PIWIK_URL}
commonweb.piwik-site-id=${PIWIK_SITE_ID}
commonweb.contactUsUrl=${CONTACT_US_URL}
commonweb.developer-url=${DEVELOPER_URL}
# OpenTelemetry
management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:}/v1/metrics
